"""initial migration

Revision ID: 3ccbbdc89981
Revises: 
Create Date: 2022-05-12 22:14:49.127959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ccbbdc89981'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry', sa.String(length=255), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entry_date_created'), 'journal_entry', ['date_created'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('last_session', sa.DateTime(), nullable=True),
    sa.Column('user_rating', sa.Integer(), nullable=True),
    sa.Column('plant_state', sa.Integer(), nullable=True),
    sa.Column('pot_state', sa.Integer(), nullable=True),
    sa.Column('mood_recorded', sa.Boolean(), nullable=True),
    sa.Column('journal_recorded', sa.Boolean(), nullable=True),
    sa.Column('activity_one_complete', sa.Boolean(), nullable=True),
    sa.Column('activity_two_complete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_user_rating'), 'user', ['user_rating'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_user_rating'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_journal_entry_date_created'), table_name='journal_entry')
    op.drop_table('journal_entry')
    # ### end Alembic commands ###
