"""initial migration

Revision ID: d75737440104
Revises: 
Create Date: 2022-05-15 12:35:04.627962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd75737440104'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journalprompt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('plant_state', sa.Integer(), nullable=True),
    sa.Column('pot_state', sa.Integer(), nullable=True),
    sa.Column('user_rating', sa.Integer(), nullable=True),
    sa.Column('mood_recorded', sa.Boolean(), nullable=True),
    sa.Column('journal_recorded', sa.Boolean(), nullable=True),
    sa.Column('breathing_complete', sa.Boolean(), nullable=True),
    sa.Column('meditation_complete', sa.Boolean(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('last_session', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('journalentry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry', sa.String(length=255), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('journal_prompt_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['journal_prompt_id'], ['journalprompt.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journalentry_date_created'), 'journalentry', ['date_created'], unique=False)
    op.create_table('mood',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mood', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mood_date_created'), 'mood', ['date_created'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mood_date_created'), table_name='mood')
    op.drop_table('mood')
    op.drop_index(op.f('ix_journalentry_date_created'), table_name='journalentry')
    op.drop_table('journalentry')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_table('journalprompt')
    # ### end Alembic commands ###
